language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  - PACKAGE="telnet" OCAML_VERSION=4.02
  - PACKAGE="telnet" OCAML_VERSION=4.03
  - PACKAGE="telnet" OCAML_VERSION=4.02 DEPOPTS="mirage-types ipaddr io-page" TESTS=false
  - PACKAGE="telnet" OCAML_VERSION=4.03 DEPOPTS="mirage-types ipaddr io-page" TESTS=false
notifications:
  email: false
