language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - PACKAGE="telnet"
  matrix:
    - OCAML_VERSION=4.02
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.02 DEPOPTS="mirage-types ipaddr io-page" TESTS=false
    - OCAML_VERSION=4.04 DEPOPTS="mirage-types ipaddr io-page" TESTS=false
notifications:
  email: false
